;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Cum Mar 11 2016
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
CODE    SEGMENT PARA 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STAK
STAK    SEGMENT PARA STACK 'STACK'
        DW 20 DUP(?)
STAK    ENDS

DATA    SEGMENT PARA 'DATA'
SERIALDATA  DB 15 DUP (?)
DATA    ENDS

START PROC FAR
        MOV AX, DATA
	MOV DS, AX
	
	;RESET
	MOV DX, 0104h
	MOV AL, 01001101B
	OUT DX, AL
	MOV AL, 40H
	OUT DX, AL
	;MOD
	MOV AL, 01001101B
	OUT DX, AL
	;KONTROL
	MOV AL, 00010101B
	OUT DX, AL
	
	
ENDLESS:

	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	;;;;;HABESLESMEYI BASLAT;;;;;
	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	MOV DX, 0104H
TEKRAR1:
	
	IN AL, DX
	AND AL, 01H
	JZ TEKRAR1
	
	;S KARAKTERI
	MOV DX, 0100H
	MOV AL, 53H
	OUT DX, AL
	
	MOV DX, 0104H
TEKRAR2:
	IN AL, DX
	AND AL, 01H
	JZ TEKRAR2
	
	;R KARAKTERI
	MOV DX, 0100H
	MOV AL, 52H
	OUT DX, AL 
	
	;;;;;;;;;;;;;;;;
	;;;;RECIEVE;;;;;
	;;;;;;;;;;;;;;;;
	
	MOV DX, 0104H
T3:	IN AL, DX
	TEST AL, 02H
	JZ T3
	
	MOV DX, 0100H
	IN AL, DX
	SHR AL,1
	
	CMP AL,58H ;X KARAKTERI
	JZ ENDLESS
	CMP AL,41H  ;A KARAKTERI
	JNZ ENDLESS
	
	;VERI ILETISIMI GERCEKLESEBILIR
	
	;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	;;;;;HABESLESMEYI BITIR;;;;;
	;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	
	MOV DX, 0104H
TEKRAR3:
	
	IN AL, DX
	AND AL, 01H
	JZ TEKRAR3
	
	;S KARAKTERI
	MOV DX, 0100H
	MOV AL, 53H
	OUT DX, AL
	
	MOV DX, 0104H
TEKRAR4:
	IN AL, DX
	AND AL, 01H
	JZ TEKRAR4
	
	;T KARAKTERI
	MOV DX, 0100H
	MOV AL, 54H
	OUT DX, AL 
			
			
	;;;;;;;;;;;;;;;;
	;;;;RECIEVE;;;;;
	;;;;;;;;;;;;;;;;
	
	MOV DX, 0104H
T4:	IN AL, DX
	TEST AL, 02H
	JZ T4
	
	MOV DX, 0100H
	IN AL, DX
	SHR AL,1
	
	CMP AL,58H ;X KARAKTERI
	JZ ENDLESS 
	CMP AL,50H  ;P KARAKTERI
	JZ ENDLESS   ;ILETISIM SONLANDI
	
	
	
        JMP ENDLESS



	
RETF
START ENDP
	

	
CODE    ENDS
        END START